# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Learning English in Kyushu
tagline:             'with an Englishman'
description:         'English classes in Miyakonojo'
url:                 '/KyushuEnglish'
baseurl:             '/KyushuEnglish'
paginate:            8

# About/contact
author:
  name:             CPS
  url:              https://kyushuenglish.github.io/
  email:            cstarkjp@gmail.com
