# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Study English with an Englishman!"
tagline:             ''
description:         'English classes in Miyakonojo with an English professor'
url:                 '/KyushuEnglish'
baseurl:             '/'
paginate:            8

# About/contact
author:
  name:             CPS
  url:              https://kyushuenglish.github.io/
  email:            cstarkjp@gmail.com
